import { NextRequest, NextResponse } from "next/server"
import { SPOTIFY_API_BASE_URL } from "@/lib/spotify/constants"
import { getSpotifySession } from "@/lib/spotify/session"

async function spotifyPost<T>(
  path: string,
  body: unknown,
  accessToken: string,
): Promise<T> {
  const res = await fetch(`${SPOTIFY_API_BASE_URL}${path}`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
    cache: "no-store",
  })

  if (!res.ok) {
    const detail = await res.text()
    throw new Error(`Spotify ${path} failed (${res.status}): ${detail}`)
  }

  return (await res.json()) as T
}

export async function POST(request: NextRequest) {
  const session = await getSpotifySession()

  if (!session.spotifyUserId || !session.accessToken) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  let trackUris: unknown
  try {
    const body = (await request.json()) as { trackUris?: unknown }
    trackUris = body.trackUris
  } catch {
    return NextResponse.json({ error: "Invalid request body" }, { status: 400 })
  }

  if (
    !Array.isArray(trackUris) ||
    trackUris.length === 0 ||
    trackUris.some((u) => typeof u !== "string" || !u.startsWith("spotify:track:"))
  ) {
    return NextResponse.json(
      { error: "trackUris must be a non-empty array of spotify:track: URIs" },
      { status: 400 },
    )
  }

  const safeUris = trackUris as string[]

  try {
    const date = new Date().toLocaleDateString("en-US", { month: "short", year: "numeric" })

    // 1. Create the playlist
    const playlist = await spotifyPost<{ id: string; external_urls: { spotify: string } }>(
      `/users/${session.spotifyUserId}/playlists`,
      {
        name: `Escape the Bubble — ${date}`,
        description:
          "Artists the algorithm was filtering out. Generated by Unwrapped (unwrapped-one.vercel.app).",
        public: true,
      },
      session.accessToken,
    )

    // 2. Add tracks (Spotify allows max 100 per request; we have at most ~10)
    await spotifyPost(
      `/playlists/${playlist.id}/tracks`,
      { uris: safeUris },
      session.accessToken,
    )

    return NextResponse.json({ playlistUrl: playlist.external_urls.spotify })
  } catch (err) {
    console.error("[escape/playlist]", err)
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Failed to create playlist" },
      { status: 502 },
    )
  }
}
