import Link from "next/link"
import { notFound } from "next/navigation"
import type { Metadata } from "next"

export const revalidate = 3600

import { computeBubbleScore } from "@/lib/analysis/bubble-score"
import { readCachedSpotifyProfile } from "@/lib/cache/spotify-profile-cache"
import { mockProfile } from "@/lib/data/mock-profile"
import { formatPercent } from "@/lib/format"

type Props = { params: Promise<{ userId: string }> }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { userId } = await params
  const profile =
    userId === mockProfile.userId
      ? mockProfile
      : await readCachedSpotifyProfile(userId, { ignoreTtl: true })
  if (!profile) return { title: "Unwrapped" }
  const score = computeBubbleScore(profile, "medium_term")
  const top3 = score.genreDistribution.slice(0, 3).map((g) => g.genre).join(", ")
  return {
    title: `${profile.displayName}'s Genre Fingerprint — ${top3}`,
    description: `See how ${profile.displayName}'s listening breaks down by genre. Generated by Unwrapped.`,
  }
}

export default async function FingerprintSharePage({ params }: Props) {
  const { userId } = await params
  const profile =
    userId === mockProfile.userId
      ? mockProfile
      : await readCachedSpotifyProfile(userId, { ignoreTtl: true })

  if (!profile) notFound()

  const score = computeBubbleScore(profile, "medium_term")

  if (!score.hasGenreMetadata) {
    return (
      <main className="mx-auto flex min-h-[calc(100vh-84px)] w-full max-w-2xl flex-col justify-center px-5 py-10 sm:px-8">
        <section className="panel p-8 text-center">
          <p className="text-lg font-semibold text-[var(--text-strong)]">Genre data unavailable</p>
          <p className="mt-2 text-sm text-[var(--text-muted)]">
            Spotify didn&apos;t return genre metadata for this profile.
          </p>
          <Link href="/" className="button-primary mt-6 inline-flex">
            See your own Unwrapped
          </Link>
        </section>
      </main>
    )
  }

  const genres = score.genreDistribution.slice(0, 8)
  const maxShare = genres[0]?.share ?? 1

  return (
    <main className="mx-auto flex min-h-[calc(100vh-84px)] w-full max-w-2xl flex-col justify-center px-5 py-10 sm:px-8">
      <section className="panel panel-glow flex flex-col gap-8 p-8 sm:p-10">
        <div>
          <p className="eyebrow">{profile.displayName}&apos;s Genre Fingerprint</p>
          <h1 className="mt-2 text-2xl font-semibold text-[var(--text-strong)]">
            Taste, mapped by algorithm
          </h1>
          <p className="mt-2 text-sm text-[var(--text-muted)]">
            Based on 6-month listening history.
            {score.score >= 55 && " High concentration — deep in the loop."}
            {score.score < 30 && " Low concentration — unusually broad taste."}
          </p>
        </div>

        {/* Genre bars */}
        <div className="flex flex-col gap-4">
          {genres.map((g, i) => (
            <div key={g.genre} className="flex items-center gap-3">
              <span className="w-5 shrink-0 text-right text-xs tabular-nums text-[var(--text-muted)]">
                {i + 1}
              </span>
              <div className="flex-1 flex flex-col gap-1.5">
                <div className="flex justify-between">
                  <span className="text-sm capitalize text-[var(--text-soft)]">{g.genre}</span>
                  <span className="text-xs tabular-nums text-[var(--text-muted)]">
                    {formatPercent(g.share)}
                  </span>
                </div>
                <div className="h-2 rounded-full bg-white/8 overflow-hidden">
                  <div
                    className="h-full rounded-full bg-[var(--accent)]"
                    style={{
                      width: `${(g.share / maxShare) * 100}%`,
                      opacity: i === 0 ? 1 : Math.max(0.25, 1 - i * 0.1),
                    }}
                  />
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* HHI context */}
        <div className="rounded-2xl border border-white/10 bg-black/20 p-4">
          <p className="text-sm text-[var(--text-muted)]">
            Concentration score (HHI):{" "}
            <span className="font-semibold text-[var(--text-soft)]">
              {Math.round(score.score)}
            </span>{" "}
            — {score.tier.toLowerCase()}. Higher = taste is narrowing around the algorithm&apos;s
            recommendations.
          </p>
        </div>

        <div className="flex flex-wrap gap-3 border-t border-white/8 pt-2">
          <Link href="/" className="button-primary">
            See your own Unwrapped
          </Link>
          <Link href={`/share/${userId}`} className="button-secondary">
            Full snapshot
          </Link>
        </div>
      </section>
    </main>
  )
}
